<a href="https://colab.research.google.com/github/abhisekchaudhuri/PythonLabs/blob/AI-Explorations/testingTF1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
import tensorflow as tf

x = np.array([[200, 10], [150, 20], [100, 45]])

# Correct way to define a Dense layer in TensorFlow Keras
# You need to specify the number of units (neurons) in the layer
# and optionally the activation function.
# For the first layer, it's good practice to define input_shape.
layer1 = tf.keras.layers.Dense(units=3, activation='sigmoid')
a1=layer1(x)
print("Output of layer 1 (a1):")
print(a1)

layer2 = tf.keras.layers.Dense(units=2, activation='sigmoid')
a2=layer2(a1)
print("Output of layer 2 (a2):")
print(a2)

layer3 = tf.keras.layers.Dense(units=1, activation='sigmoid')
a3=layer3(a2)
print("Output of layer 3 (a3):")
print(a3)

# Generate a y_hat for each individual input row
y_hat = tf.cast(a3 >= 0.5, tf.int32)

print(f"Predicted y_hat for each row: {y_hat.numpy().flatten()}")

Output of layer 1 (a1):
tf.Tensor(
[[1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]], shape=(3, 3), dtype=float32)
Output of layer 2 (a2):
tf.Tensor(
[[0.44778156 0.38126343]
 [0.44778156 0.38126343]
 [0.44778156 0.38126343]], shape=(3, 2), dtype=float32)
Output of layer 3 (a3):
tf.Tensor(
[[0.562156]
 [0.562156]
 [0.562156]], shape=(3, 1), dtype=float32)
Predicted y_hat for each row: [1 1 1]
