<a href="https://colab.research.google.com/github/abhisekchaudhuri/PythonLabs/blob/AI-Explorations/testingTF1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import tensorflow as tf

y_hat=0

#x = np.array([[200, 10], [150, 20], [100, 45]])
x = np.array([[200, 10]])

# Correct way to define a Dense layer in TensorFlow Keras
# You need to specify the number of units (neurons) in the layer
# and optionally the activation function.
# For the first layer, it's good practice to define input_shape.
layer1 = tf.keras.layers.Dense(units=3, activation='sigmoid')
a1=layer1(x)
print("Output of layer 1 (a1):")
print(a1)

layer2 = tf.keras.layers.Dense(units=2, activation='sigmoid')
a2=layer2(a1)
print("Output of layer 2 (a2):")
print(a2)

layer3 = tf.keras.layers.Dense(units=1, activation='sigmoid')
a3=layer3(a2)
print("Output of layer 3 (a3):")
print(a3)

# Corrected if/else syntax and handling of tensor comparison
# Using tf.reduce_all to check if all elements in a2 are >= 0.5
# If you meant to check the mean, use: tf.reduce_mean(a2) >= 0.5
if tf.reduce_all(a2 >= 0.5):
  y_hat=1
else:
  y_hat=0

print(f"Predicted y_hat: {y_hat}")

Output of layer 1 (a1):
tf.Tensor([[9.999945e-01 1.000000e+00 9.019206e-37]], shape=(1, 3), dtype=float32)
Output of layer 2 (a2):
tf.Tensor([[0.59786   0.8345166]], shape=(1, 2), dtype=float32)
Output of layer 3 (a3):
tf.Tensor([[0.25652647]], shape=(1, 1), dtype=float32)
Predicted y_hat: 1
